---
cf-manifest-vars: &cf-manifest-vars
  vars:
    APP_NAME: ((name))
    CDN_DB_NAME: ((cdn_db_name))
    DOMAIN_DB_NAME: ((domain_db_name))

jobs:

- name: reconfigure
  serial: true
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
  - get: secrets
    # Remember to manually trigger a new build if you upload a new version
    # of the credentials file.
    trigger: false
  - set_pipeline: ((name))
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml

- name: test
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
    passed: [reconfigure]

  - put: dev-docker-image
    # We push this docker image _only_ so that we can use it in the next task
    # below.  :shrug: concourse.
    params:
      build: src
      dockerfile: src/docker/Dockerfile.dev
      tag_as_latest: true
      cache: true

  - task: test
    # Run the tests using the image pushed above.
    image: dev-docker-image
    config:
      platform: linux
      params:
        TMPDIR: /tmp
      run:
        path: /app/docker/tests

- name: dev
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [test]
    - get: pipeline-tasks
  - put: cf-dev
    params:
      path: src
      manifest: src/manifest.yml
      show_app_log: true
      <<: *cf-manifest-vars
      environment_variables:
        ENV: development
        DNS_ROOT_DOMAIN: ((dev-dns-root-domain))
        DATABASE_ENCRYPTION_KEY: ((dev-database-encryption-key))
        AWS_COMMERCIAL_REGION: ((dev-aws-commercial-region))
        AWS_COMMERCIAL_ACCESS_KEY_ID: ((dev-aws-commercial-access-key-id))
        AWS_COMMERCIAL_SECRET_ACCESS_KEY: ((dev-aws-commercial-secret-access-key))
        ROUTE53_HOSTED_ZONE_ID: ((dev-route53-hosted-zone-id))
        ALB_HOSTED_ZONE_ID: ((dev-alb-hosted-zone-id))
        CF_USERNAME: ((dev-cf-username))
        CF_PASSWORD: ((dev-cf-password))
        CF_API_ENDPOINT: ((dev-cf-api-endpoint))
        SMTP_HOST: ((dev-smtp-host))
        SMTP_FROM: ((dev-smtp-from))
        SMTP_CERT: ((dev-smtp-cert))
        SMTP_USER: ((dev-smtp-user))
        SMTP_PASS: ((dev-smtp-pass))
        SMTP_PORT: ((dev-smtp-port))
        SMTP_TO: ((dev-smtp-to))

  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy external-domain-broker-migrator on development
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed external-domain-broker-migrator on development
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))


- name: staging
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [dev]
    - get: pipeline-tasks
  - put: cf-staging
    params:
      path: src
      manifest: src/manifest.yml
      show_app_log: true
      <<: *cf-manifest-vars
      environment_variables:
        ENV: staging
        DNS_ROOT_DOMAIN: ((staging-dns-root-domain))
        DATABASE_ENCRYPTION_KEY: ((staging-database-encryption-key))
        AWS_COMMERCIAL_REGION: ((staging-aws-commercial-region))
        AWS_COMMERCIAL_ACCESS_KEY_ID: ((staging-aws-commercial-access-key-id))
        AWS_COMMERCIAL_SECRET_ACCESS_KEY: ((staging-aws-commercial-secret-access-key))
        ROUTE53_HOSTED_ZONE_ID: ((staging-route53-hosted-zone-id))
        ALB_HOSTED_ZONE_ID: ((staging-alb-hosted-zone-id))
        CF_USERNAME: ((staging-cf-username))
        CF_PASSWORD: ((staging-cf-password))
        CF_API_ENDPOINT: ((staging-cf-api-endpoint))
        SMTP_HOST: ((staging-smtp-host))
        SMTP_FROM: ((staging-smtp-from))
        SMTP_CERT: ((staging-smtp-cert))
        SMTP_USER: ((staging-smtp-user))
        SMTP_PASS: ((staging-smtp-pass))
        SMTP_PORT: ((staging-smtp-port))
        SMTP_TO: ((staging-smtp-to))

  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy external-domain-broker-migrator on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed external-domain-broker-migrator on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

############################
#  RESOURCES

resources:

- name: secrets
  type: s3-iam
  icon: cloud-lock
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: src
  type: git
  icon: github-circle
  check_every: 10s
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))

- name: dev-docker-image
  type: docker-image
  icon: docker
  source:
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-image-dev))

- name: cf-dev
  type: cf
  icon: cloud-upload
  source:
    api: ((dev-cf-api-endpoint))
    username: ((dev-cf-username))
    password: ((dev-cf-password))
    organization: ((migrator-organization))
    space: ((migrator-space))

- name: cf-staging
  type: cf
  icon: cloud-upload
  source:
    api: ((staging-cf-api-endpoint))
    username: ((staging-cf-username))
    password: ((staging-cf-password))
    organization: ((migrator-organization))
    space: ((migrator-space))

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

- name: pipeline-tasks
  type: git
  icon: github-circle
  source:
    uri: ((pipeline-tasks-git-url))
    branch: ((pipeline-tasks-git-branch))


############################
#  RESOURCE TYPES

resource_types:

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
